name: Flutter analyze
on:
  pull_request:
    types:
        - opened
    branches:
        - main

permissions:
  contents: read

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze
